apiVersion: network.operator.linode.io/v1alpha1
kind: Vlan
metadata:
  labels:
    app.kubernetes.io/name: vlan-operator
    app.kubernetes.io/managed-by: kustomize
  name: vlan-sample
spec:
  # TODO(user): Add fields here
  vlanCidr: 172.16.0.5/24
  vlanLabel: kube-vlan
  # interval: 10s
  apiKeySecret:
    name: linode-api-key
    key: api-key
    namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: linode-api-key
type: Opaque
stringData:
  api-key: "<API_KEY>"